In [1]:
import pandas as pd
import urllib.parse

limit = urllib.parse.quote("date_extract_y(grade_date) = 2018")
food_scores = pd.read_csv("https://data.cityofnewyork.us/resource/43nn-pn8j.csv?$where=" + limit)

food_scores.head()

,camis,dba,boro,building,street,zipcode,phone,cuisine_description,inspection_date,action,...,record_date,inspection_type,latitude,longitude,community_board,council_district,census_tract,bin,bbl,nta
0,40703739,JOSIE WOOD'S PUB,Manhattan,11,WAVERLY PLACE,10003.0,2122289909,American,2018-07-27T00:00:00.000,Violations were cited in the following area(s).,...,2019-11-07T06:00:54.000,Cycle Inspection / Initial Inspection,40.730034,-73.994173,102.0,1.0,5900.0,1008838.0,1005480040,MN23
1,40402369,COLONY CLUB,Manhattan,564,PARK AVENUE,10065.0,2128384200,American,2018-11-19T00:00:00.000,Violations were cited in the following area(s).,...,2019-11-07T06:00:54.000,Cycle Inspection / Re-inspection,40.765044,-73.968254,108.0,4.0,11401.0,1040899.0,1013770033,MN40
2,40944804,BLAGGARD'S PUB,Manhattan,8,WEST 38 STREET,10018.0,2123822611,Irish,2018-11-23T00:00:00.000,Violations were cited in the following area(s).,...,2019-11-07T06:00:54.000,Cycle Inspection / Re-inspection,40.751208,-73.983354,105.0,4.0,8400.0,1075696.0,1008390055,MN17
3,41523349,STEVEN RESTAURANT,Bronx,2233,BOSTON ROAD,10467.0,7186527778,"Latin (Cuban, Dominican, Puerto Rican, South &...",2018-04-03T00:00:00.000,Violations were cited in the following area(s).,...,2019-11-07T06:00:54.000,Cycle Inspection / Initial Inspection,40.858401,-73.867912,211.0,15.0,33201.0,2049738.0,2043390012,BX07
4,41462617,MIKE'S UNICORN DINER,Staten Island,2944,VICTORY BOULEVARD,10314.0,7184942129,American,2018-08-21T00:00:00.000,Violations were cited in the following area(s).,...,2019-11-07T06:00:54.000,Cycle Inspection / Re-inspection,40.607389,-74.160675,502.0,50.0,27301.0,5034978.0,5020720057,SI05

In [2]:
pd.set_option('display.max.columns', None)
pd.set_option('display.max.rows',None)
pd.set_option('display.max_colwidth', -1)
food_scores.head()

,camis,dba,boro,building,street,zipcode,phone,cuisine_description,inspection_date,action,violation_code,violation_description,critical_flag,score,grade,grade_date,record_date,inspection_type,latitude,longitude,community_board,council_district,census_tract,bin,bbl,nta
0,40703739,JOSIE WOOD'S PUB,Manhattan,11,WAVERLY PLACE,10003.0,2122289909,American,2018-07-27T00:00:00.000,Violations were cited in the following area(s).,10F,"Non-food contact surface improperly constructed. Unacceptable material used. Non-food contact surface or equipment improperly maintained and/or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.",N,13,A,2018-07-27T00:00:00.000,2019-11-07T06:00:54.000,Cycle Inspection / Initial Inspection,40.730034,-73.994173,102.0,1.0,5900.0,1008838.0,1005480040,MN23
1,40402369,COLONY CLUB,Manhattan,564,PARK AVENUE,10065.0,2128384200,American,2018-11-19T00:00:00.000,Violations were cited in the following area(s).,04N,"Filth flies or food/refuse/sewage-associated (FRSA) flies present in facilityâ€™s food and/or non-food areas. Filth flies include house flies, little house flies, blow flies, bottle flies and flesh flies. Food/refuse/sewage-associated flies include fruit flies, drain flies and Phorid flies.",Y,11,A,2018-11-19T00:00:00.000,2019-11-07T06:00:54.000,Cycle Inspection / Re-inspection,40.765044,-73.968254,108.0,4.0,11401.0,1040899.0,1013770033,MN40
2,40944804,BLAGGARD'S PUB,Manhattan,8,WEST 38 STREET,10018.0,2123822611,Irish,2018-11-23T00:00:00.000,Violations were cited in the following area(s).,02B,Hot food item not held at or above 140Âº F.,Y,14,B,2018-11-23T00:00:00.000,2019-11-07T06:00:54.000,Cycle Inspection / Re-inspection,40.751208,-73.983354,105.0,4.0,8400.0,1075696.0,1008390055,MN17
3,41523349,STEVEN RESTAURANT,Bronx,2233,BOSTON ROAD,10467.0,7186527778,"Latin (Cuban, Dominican, Puerto Rican, South & Central American)",2018-04-03T00:00:00.000,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,N,13,A,2018-04-03T00:00:00.000,2019-11-07T06:00:54.000,Cycle Inspection / Initial Inspection,40.858401,-73.867912,211.0,15.0,33201.0,2049738.0,2043390012,BX07
4,41462617,MIKE'S UNICORN DINER,Staten Island,2944,VICTORY BOULEVARD,10314.0,7184942129,American,2018-08-21T00:00:00.000,Violations were cited in the following area(s).,10F,"Non-food contact surface improperly constructed. Unacceptable material used. Non-food contact surface or equipment improperly maintained and/or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.",N,12,A,2018-08-21T00:00:00.000,2019-11-07T06:00:54.000,Cycle Inspection / Re-inspection,40.607389,-74.160675,502.0,50.0,27301.0,5034978.0,5020720057,SI05

In [3]:
food_scores['cuisine_description'].value_counts()

American                                                            236
Chinese                                                             95
Pizza                                                               49
CafÃ©/Coffee/Tea                                                     48
Latin (Cuban, Dominican, Puerto Rican, South & Central American)    43
Mexican                                                             38
Caribbean                                                           37
Bakery                                                              37
Italian                                                             35
Japanese                                                            31
Spanish                                                             30
Pizza/Italian                                                       21
Indian                                                              19
Delicatessen                                                        18
Asian                                                               17
Mediterranean                                                       17
Chicken                                                             16
Jewish/Kosher                                                       16
Korean                                                              13
Juice, Smoothies, Fruit Salads                                      13
French                                                              12
Donuts                                                              12
Thai                                                                10
Ice Cream, Gelato, Yogurt, Ices                                     10
Sandwiches                                                          9
Irish                                                               9
Hamburgers                                                          8
Middle Eastern                                                      8
Vietnamese/Cambodian/Malaysia                                       7
Bagels/Pretzels                                                     6
Sandwiches/Salads/Mixed Buffet                                      5
Salads                                                              5
Eastern European                                                    5
Bangladeshi                                                         4
Soul Food                                                           4
Seafood                                                             4
Afghan                                                              3
Other                                                               3
Tapas                                                               3
Greek                                                               3
Russian                                                             3
Vegetarian                                                          3
Chinese/Cuban                                                       3
Soups & Sandwiches                                                  3
Chinese/Japanese                                                    3
Portuguese                                                          2
Bottled beverages, including water, sodas, juices, etc.             2
African                                                             2
Turkish                                                             2
Brazilian                                                           2
Moroccan                                                            2
Australian                                                          1
Continental                                                         1
Steak                                                               1
Egyptian                                                            1
Hotdogs/Pretzels                                                    1
German                                                              1
Barbecue                                                            1
Hotdogs                                                             1
Polish                                                              1
Tex-Mex                                                             1
Scandinavian                                                        1
Armenian                                                            1
Pakistani                                                           1
Peruvian                                                            1
Name: cuisine_description, dtype: int64

In [4]:
#What is the median score for the 'Bakery' cuisine type?
bakery = food_scores[['cuisine_description','score']].groupby('cuisine_description').median()
bakery

                                                                  score
cuisine_description
Afghan                                                            6.0
African                                                           37.0
American                                                          11.0
Armenian                                                          13.0
Asian                                                             13.0
Australian                                                        13.0
Bagels/Pretzels                                                   9.0
Bakery                                                            11.0
Bangladeshi                                                       17.5
Barbecue                                                          13.0
Bottled beverages, including water, sodas, juices, etc.           18.5
Brazilian                                                         11.0
CafÃ©/Coffee/Tea                                                   10.5
Caribbean                                                         12.0
Chicken                                                           12.0
Chinese                                                           12.0
Chinese/Cuban                                                     13.0
Chinese/Japanese                                                  16.0
Continental                                                       13.0
Delicatessen                                                      13.0
Donuts                                                            6.0
Eastern European                                                  11.0
Egyptian                                                          37.0
French                                                            12.0
German                                                            11.0
Greek                                                             12.0
Hamburgers                                                        9.5
Hotdogs                                                           8.0
Hotdogs/Pretzels                                                  3.0
Ice Cream, Gelato, Yogurt, Ices                                   11.0
Indian                                                            13.0
Irish                                                             11.0
Italian                                                           12.0
Japanese                                                          12.0
Jewish/Kosher                                                     12.0
Juice, Smoothies, Fruit Salads                                    11.0
Korean                                                            13.0
Latin (Cuban, Dominican, Puerto Rican, South & Central American)  12.0
Mediterranean                                                     12.0
Mexican                                                           12.0
Middle Eastern                                                    10.5
Moroccan                                                          28.5
Other                                                             11.0
Pakistani                                                         15.0
Peruvian                                                          12.0
Pizza                                                             12.0
Pizza/Italian                                                     12.0
Polish                                                            10.0
Portuguese                                                        8.0
Russian                                                           10.0
Salads                                                            13.0
Sandwiches                                                        11.0
Sandwiches/Salads/Mixed Buffet                                    10.0
Scandinavian                                                      12.0
Seafood                                                           17.5
Soul Food                                                         13.5
Soups & Sandwiches                                                13.0
Spanish                                                           12.0
Steak                                                             42.0
Tapas                                                             12.0
Tex-Mex                                                           12.0
Thai                                                              12.5
Turkish                                                           12.0
Vegetarian                                                        10.0
Vietnamese/Cambodian/Malaysia                                     9.0

In [5]:
#Q3: Which cuisine type has the best (i.e., the lowest) median score? (Hint: use .sort_values)
bakery.sort_values('score')

                                                                  score
cuisine_description
Hotdogs/Pretzels                                                  3.0
Afghan                                                            6.0
Donuts                                                            6.0
Portuguese                                                        8.0
Hotdogs                                                           8.0
Bagels/Pretzels                                                   9.0
Vietnamese/Cambodian/Malaysia                                     9.0
Hamburgers                                                        9.5
Sandwiches/Salads/Mixed Buffet                                    10.0
Russian                                                           10.0
Polish                                                            10.0
Vegetarian                                                        10.0
CafÃ©/Coffee/Tea                                                   10.5
Middle Eastern                                                    10.5
Bakery                                                            11.0
Sandwiches                                                        11.0
Other                                                             11.0
Irish                                                             11.0
Ice Cream, Gelato, Yogurt, Ices                                   11.0
American                                                          11.0
German                                                            11.0
Juice, Smoothies, Fruit Salads                                    11.0
Brazilian                                                         11.0
Eastern European                                                  11.0
Italian                                                           12.0
Scandinavian                                                      12.0
Spanish                                                           12.0
Tapas                                                             12.0
Tex-Mex                                                           12.0
Pizza/Italian                                                     12.0
Pizza                                                             12.0
Peruvian                                                          12.0
Caribbean                                                         12.0
Chicken                                                           12.0
Mexican                                                           12.0
Latin (Cuban, Dominican, Puerto Rican, South & Central American)  12.0
Mediterranean                                                     12.0
French                                                            12.0
Jewish/Kosher                                                     12.0
Japanese                                                          12.0
Chinese                                                           12.0
Turkish                                                           12.0
Greek                                                             12.0
Thai                                                              12.5
Australian                                                        13.0
Asian                                                             13.0
Barbecue                                                          13.0
Salads                                                            13.0
Continental                                                       13.0
Armenian                                                          13.0
Korean                                                            13.0
Indian                                                            13.0
Chinese/Cuban                                                     13.0
Soups & Sandwiches                                                13.0
Delicatessen                                                      13.0
Soul Food                                                         13.5
Pakistani                                                         15.0
Chinese/Japanese                                                  16.0
Bangladeshi                                                       17.5
Seafood                                                           17.5
Bottled beverages, including water, sodas, juices, etc.           18.5
Moroccan                                                          28.5
African                                                           37.0
Egyptian                                                          37.0
Steak                                                             42.0

In [8]:
#Q4: Which borough (here, 'boro') has the highest (worse) mean score?
boro = food_scores[['boro','score']].groupby('boro').mean()
boro.sort_values('score')

                   score
boro
Staten Island  11.741935
Manhattan      13.022785
Brooklyn       13.024691
Queens         13.260504
Bronx          13.795699

In [14]:
#Q5: Which borough has the highest count of 'A' grades?
boro = food_scores[['boro','grade']].groupby('boro')
boro['grade'].value_counts()

boro           grade
Bronx          A        66
               B        19
               C        5
               P        3
Brooklyn       A        193
               B        35
               C        14
               P        1
Manhattan      A        313
               B        60
               C        17
               P        5
Queens         A        181
               B        39
               C        16
               P        2
Staten Island  A        27
               B        3
               C        1
Name: grade, dtype: int64

In [15]:
#Q6: What's the grade most '02B' violations receive?
grade = food_scores[['grade','violation_code']].groupby('violation_code')
grade['grade'].value_counts()

violation_code  grade
02A             A        1
02B             A        20
                B        9
                C        3
02C             A        1
02F             A        1
02G             A        38
                B        12
                C        2
02H             A        10
                B        5
                C        1
02I             A        2
                C        1
03A             A        3
03B             A        1
03C             P        1
04A             A        9
                B        3
04C             A        5
04D             B        1
04H             A        17
                B        6
04J             A        3
04K             B        1
04L             A        40
                B        19
                C        4
                P        2
04M             A        17
                B        4
                C        2
04N             A        23
                B        17
                C        6
05D             A        3
                B        1
                C        1
05E             B        1
05F             B        2
05H             C        1
06A             A        6
                B        3
06B             A        8
                B        1
                C        1
06C             A        64
                B        9
06D             A        52
                B        10
                C        2
06E             A        19
                B        2
                C        2
06F             A        11
                B        3
08A             A        76
                B        26
                C        7
                P        1
08B             A        2
08C             A        9
                B        2
                C        2
                P        1
09A             A        1
09B             A        9
                B        3
                C        1
09C             A        29
                B        2
                C        2
10A             A        4
                B        1
10B             A        61
                B        5
                C        5
10C             A        2
10D             A        4
                C        1
10E             A        8
10F             A        184
                B        7
                C        7
                P        6
10H             A        13
                B        1
                C        1
10I             A        14
10J             A        3
22F             A        3
Name: grade, dtype: int64

In [19]:
#Q7 What's the median score for '04L' violations?
o4l = food_scores[['score','violation_code']].groupby('violation_code')
o4l.median()

                score
violation_code
02A             12.0
02B             12.0
02C             12.0
02F             13.0
02G             12.0
02H             12.0
02I             12.0
03A             12.0
03B             12.0
03C             9.0
04A             12.0
04C             11.0
04D             15.0
04H             12.0
04J             10.0
04K             19.0
04L             13.0
04M             12.0
04N             14.0
05D             12.0
05E             17.0
05F             22.0
05H             96.0
06A             12.0
06B             11.0
06C             11.0
06D             12.0
06E             12.0
06F             12.5
08A             13.0
08B             5.5
08C             12.0
09A             6.0
09B             12.0
09C             12.0
10A             13.0
10B             11.0
10C             9.5
10D             9.0
10E             10.0
10F             10.0
10H             12.0
10I             9.0
10J             9.0
22F             9.0

In [20]:
#Q9 What is the median score for restaurants where the 'critical_flag' value was 'Critical'?
crit = food_scores[['score','critical_flag']].groupby('critical_flag')
crit.median()

               score
critical_flag
N              11
Y              12

In [22]:
# Q10: What is the median score for restaurants receiving a 'C' grade?
cgrade = food_scores[['grade','score']].groupby('grade')
cgrade.median()

       score
grade
A      11
B      21
C      37
P      9