In [1]:
import sqlalchemy as sqla

import pandas as pd

db = sqla.create_engine("mysql+pymysql://anonymous:@ensembldb.ensembl.org:3306/aedes_aegypti_core_48_1b")

Question 1 & 2

In [2]:
pd.read_sql('SHOW TABLES;', db)

       Tables_in_aedes_aegypti_core_48_1b
0                              alt_allele
1                                analysis
2                    analysis_description
3                                assembly
4                      assembly_exception
5                             attrib_type
6                            coord_system
7                         density_feature
8                            density_type
9                                   ditag
10                          ditag_feature
11                                    dna
12                      dna_align_feature
13                                   dnac
14                                   exon
15                         exon_stable_id
16                        exon_transcript
17                            external_db
18                       external_synonym
19                                   gene
20                           gene_archive
21                            gene_attrib
22                         gene_stable_id
23                                go_xref
24                          identity_xref
25                               interpro
26                              karyotype
27                                    map
28                        mapping_session
29                                 marker
..                                    ...
44                        prediction_exon
45                  prediction_transcript
46                  protein_align_feature
47                        protein_feature
48                                    qtl
49                            qtl_feature
50                            qtl_synonym
51                      regulatory_factor
52               regulatory_factor_coding
53                     regulatory_feature
54              regulatory_feature_object
55               regulatory_search_region
56                       repeat_consensus
57                         repeat_feature
58                             seq_region
59                      seq_region_attrib
60                         simple_feature
61                        stable_id_event
62                     supporting_feature
63                             transcript
64                      transcript_attrib
65                   transcript_stable_id
66          transcript_supporting_feature
67                            translation
68                     translation_attrib
69                  translation_stable_id
70  unconventional_transcript_association
71                        unmapped_object
72                        unmapped_reason
73                                   xref

[74 rows x 1 columns]

For questions 3 and 4

In [3]:
gene = pd.read_sql('SELECT * FROM gene;', db)

gene.head(20)

,gene_id,biotype,analysis_id,seq_region_id,seq_region_start,seq_region_end,seq_region_strand,display_xref_id,source,status,description,is_current
0,1,protein_coding,1,3016,1756998,1757815,1,NaN,VectorBase,NOVEL,low molecular weight protein-tyrosine-phosphatase,1
1,2,protein_coding,1,564,47363,55875,1,NaN,VectorBase,NOVEL,conserved hypothetical protein,1
2,3,protein_coding,1,3525,378111,391870,1,NaN,VectorBase,NOVEL,phosphatidylserine decarboxylase,1
3,4,protein_coding,1,4051,6001,7010,1,104.0,VectorBase,KNOWN,60S ribosomal protein L23,1
4,5,protein_coding,1,2170,22562,25978,1,NaN,VectorBase,NOVEL,heat shock protein,1
5,6,protein_coding,1,4187,908281,910123,1,NaN,VectorBase,NOVEL,organic cation transporter,1
6,7,protein_coding,1,1877,1393691,1439463,-1,NaN,VectorBase,NOVEL,lava lamp protein,1
7,8,protein_coding,1,1444,462228,471603,1,NaN,VectorBase,NOVEL,hypothetical protein,1
8,9,protein_coding,1,884,487753,509362,-1,NaN,VectorBase,NOVEL,lkb1 interacting protein,1
9,10,protein_coding,1,6,52902,64888,-1,2880.0,VectorBase,KNOWN,"NADH:ubiquinone dehydrogenase, putative",1
10,11,protein_coding,1,2623,74491,80479,-1,NaN,VectorBase,NOVEL,chromatin assembly factor i P60 subunit,1
11,12,protein_coding,1,647,112794,117072,1,NaN,VectorBase,NOVEL,conserved hypothetical protein,1
12,13,protein_coding,1,2070,217183,244449,-1,NaN,VectorBase,NOVEL,conserved hypothetical protein,1
13,14,protein_coding,1,4313,720570,733967,1,NaN,VectorBase,NOVEL,conserved hypothetical protein,1
14,15,protein_coding,1,3393,39058,40712,-1,NaN,VectorBase,NOVEL,conserved hypothetical protein,1
15,16,protein_coding,1,3516,933037,933836,1,NaN,VectorBase,NOVEL,n-acetyltransferase,1
16,17,protein_coding,1,3177,1705587,1707906,1,NaN,VectorBase,NOVEL,conserved hypothetical protein,1
17,18,protein_coding,1,3695,1399216,1403786,1,NaN,VectorBase,NOVEL,chloride channel protein 2,1
18,19,protein_coding,1,2183,2129667,2149785,1,NaN,VectorBase,NOVEL,methionine aminopeptidase,1
19,20,protein_coding,1,3517,142471,155553,-1,NaN,VectorBase,NOVEL,engrailed,1

For questions 5-6,

In [4]:
novel_genes = pd.read_sql('SELECT * FROM gene WHERE status = "NOVEL" ORDER BY seq_region_start;', db)

novel_genes.head(20)

,gene_id,biotype,analysis_id,seq_region_id,seq_region_start,seq_region_end,seq_region_strand,display_xref_id,source,status,description,is_current
0,1120,protein_coding,1,1344,2,8298,1,None,VectorBase,NOVEL,conserved hypothetical protein,1
1,8870,protein_coding,1,4614,7,48953,-1,None,VectorBase,NOVEL,conserved hypothetical protein,1
2,2172,protein_coding,1,2855,8,1025,-1,None,VectorBase,NOVEL,hypothetical protein,1
3,420,protein_coding,1,2717,9,30259,-1,None,VectorBase,NOVEL,conserved hypothetical protein,1
4,14691,protein_coding,1,1429,11,941,1,None,VectorBase,NOVEL,"THO complex, putative",1
5,2648,protein_coding,1,1567,16,321,1,None,VectorBase,NOVEL,conserved hypothetical protein,1
6,3308,protein_coding,1,369,16,1066,-1,None,VectorBase,NOVEL,conserved hypothetical protein,1
7,11057,protein_coding,1,2414,18,5781,-1,None,VectorBase,NOVEL,"serine protease inhibitor (serpin-2), putative",1
8,1739,protein_coding,1,1775,21,726,-1,None,VectorBase,NOVEL,conserved hypothetical protein,1
9,13810,protein_coding,1,602,24,2232,1,None,VectorBase,NOVEL,alpha-esterase,1
10,11555,protein_coding,1,4133,27,7287,1,None,VectorBase,NOVEL,conserved hypothetical protein,1
11,91,protein_coding,1,2656,28,12014,1,None,VectorBase,NOVEL,conserved hypothetical protein,1
12,13820,protein_coding,1,2970,28,554,-1,None,VectorBase,NOVEL,conserved hypothetical protein,1
13,10376,protein_coding,1,1897,31,2234,1,None,VectorBase,NOVEL,protease m1 zinc metalloprotease,1
14,10372,protein_coding,1,4039,45,1619,1,None,VectorBase,NOVEL,conserved hypothetical protein,1
15,1176,protein_coding,1,3632,52,2433,1,None,VectorBase,NOVEL,conserved hypothetical protein,1
16,9638,protein_coding,1,429,53,8288,1,None,VectorBase,NOVEL,hypothetical protein,1
17,2180,protein_coding,1,2096,58,31887,1,None,VectorBase,NOVEL,hypothetical protein,1
18,339,protein_coding,1,860,62,32573,1,None,VectorBase,NOVEL,queuine tRNA-ribosyltransferase,1
19,12420,protein_coding,1,3582,62,3129,1,None,VectorBase,NOVEL,DNA polymerase delta catalytic subunit,1

Question 7

In [5]:
analysis_description = pd.read_sql('select * from analysis_description LIMIT 100;', db)

analysis_description

,analysis_id,description,display_label,displayable,web_data
0,1,Genes were annotated by merging Ensembl and TI...,VectorBase,0,None
1,5,Interspersed repeats identified by RepeatMaske...,RepeatMask,0,None
2,4,Interspersed repeats identified by RepeatMaske...,RepeatMask,0,None
3,6,Tandem repeats identified by Tandem Repeats Fi...,TRF,1,None
4,7,Low-complexity DNA sequence identified by Dust,Dust,1,None
5,61,Liverpool University - detox array reporters,ARRAY_LIV_AEGDETOX_0.25k_v1,0,None
6,62,University of Notre Dame - TIGRTC array reporters,ARRAY_ND_TIGRTC_9.6K_v1,0,None
7,63,"University of California, Riverside - Midgut a...",ARRAY_UCR_GillMgMT_0.2K_v2,0,None
8,48,Transposable elements (TE) catalogued by Jake ...,VirginiaTech_Insect_TE,0,None
9,33,Identification of peptide low complexity seque...,Seg,1,None
10,34,Prediction of signal peptide cleavage sites by...,Signalp,1,None
11,35,Prediction of coiled-coil regions in peptides ...,ncoils,1,None
12,36,Prediction of transmembrane helices in peptide...,tmhmm,1,None
13,37,Hits to the PRINTS database (protein family/do...,Prints,1,None
14,38,PROSITE patterns,prosite_patterns,1,None
15,39,Hits to the PROSITE profiles database (protein...,prosite_profiles,1,None
16,40,Hits to the Pfam database (protein family/doma...,Pfam,1,None
17,41,Hits to the TIGRFAM database (http://www.tigr....,Tigrfam,1,None
18,42,Superfamily,Superfamily,1,None
19,43,Smart,Smart,1,None
20,44,PIRSF,PIRSF,1,None
21,97,Percentage of G/C bases in the sequence.,PercentGC,1,None
22,96,Percentage of repetetive elements for top leve...,PercentageRepeat,1,None
23,98,Known gene density features in a database as c...,knownGeneDensity,1,None

For Questions 8-9,

In [6]:
dna = pd.read_sql('select SEQUENCE from dna LIMIT 100;', db)

dna

                                             SEQUENCE
0   CGCCCCCAGCGAAGGAAGACCTTCCTTAAATACTCCAGCTGGAATG...
1   CCCGCTCACATTGTGCTTGGGGCTTTACGGCAATATACTGGGTGTC...
2   CCATGTGCATGATTTAACACTGAAATTTACTTTTTTTTTCTGTGAT...
3   TTCGCTCTCATTTGAGTATGAAGCACGATCGAAGCAAGCACAAGAA...
4   GATGGTTGGATCGTCATGTTTGCAGCCTCGACATATCATTCTTCAA...
5   GCAGCTTTCAATCCATATTACCGGGTACCCCCGTTGGTTTGACCAC...
6   AATCGACTTTAAAGTTTTGAATTTTTTTTTTCAGTCCCCCATACAA...
7   CCCCCAAAGAAACGCTTTGAGATCTATTCTAGTATTACCTAAAAAA...
8   ATTTTCAAGCCAGTCAGTCGCAACCACCCCTGTAATCACCGCGCCG...
9   TTTCCTTGCGCGGCTGTTGCTGCCTTAAGGCGGAAATCTTCCGGAT...
10  AGGTAGTTCTTTCACTCATTGATTGTCTTCAAAACCTTGTCAAGTA...
11  TAATTAATTTGGCAATTTCTGATGGTATTTTCCATCGGATATTGTG...
12  TTCTCCTCAGAAACTGAAAGCTTCTCCTCAGAAGCTGGAAAGATTC...
13  TGAGATTACCCGAATGTTTATGTAAGGTATTGGGTTTAGCACTAAA...
14  CTTACTATGCCAATGACCATTTTTGCATGCGTATATCGTGTGGCAG...
15  GGGGGTTTTCTTTTATGATGGAGAGTTGGCTTCTCCGGCTCCGTTG...
16  GCGAGGGGGAAATTCTTAGAGTTCAATTAAAGTTAATTTGAGTTAT...
17  TTTCCTCTTGAGGCCAGGTGGTTTTTTGGAAAGTCACCAATGGGTT...
18  GTTTAATTCTTTTCATTATGTTGGGACATAAAATGTGGCCCTTTTT...
19  AATATATATATATATATATATATATATATATAAATTACCAGTTGGA...
20  TCCATCTTTAGTTGGCTTAGGTAACGCAAAAGTGTATCGGTAAAGG...
21  TTCACCCGACGGCACTGCAGCAGCGCCCGCGAATACAGTCACAAAT...
22  TAACTTGATATTTTGAATGATGGTTCTTTGACTAGAATTGCAGTTC...
23  TATTTGGAATATCTCTAGAGCCAGATGCCCGATGATCAAAATCGAT...
24  CTGTGCACCCGGCCAGAGTTGTCGCTTTCGCTACTAACACATTGAC...
25  TCCACAAACCAACGTATTAAATTTGAGTCTTGGTCGGTCCAAAAAT...
26  TTTTCAGCTTAACGGATGTTTGGTTCTCAAGATTCGTGCTCTTGAA...
27  CCGCCAATCCGGAGCTTGTCTCCGATGCGGACTACTAGGGACACCC...
28  TCTCCAGATCCGTGCTCTTGAAAATTTGAAGTTTGACTTCGATTCA...
29  CCTTTTGTCTTTCGACCCTTTGGTCTTCGACCTTTTGTCATAGATT...
..                                                ...
70  TACGTGGAGTTCTTCATTCAAGGCATTCACCAACCAGCATGTTGCA...
71  CCCATTTTGCAGGGGCTCAAGAGGATTTTCACAACCCGGAAGTCGC...
72  TAAAAAAAAACATTAATTGTTTTCCTTATGCCTTGATCACTAATCT...
73  ATGTGTGACACGAGATGCGCATACGTACAAAATATATCTTAGTGAG...
74  TCCCAAAACAGAAAACGAAACATGTAGTGTATGCAGTACCATGCGG...
75  GGAAGTCAGGAGATTTCCATTACGAAAAGATCCTGGACCGACCGGG...
76  CGGGATTAAAACGGCTTAAAAATGGCTTTAAATGATTTTAAATAGC...
77  CAGTCCAGTTATTAGATACAAAATTGATGTCATTCGACAAAGTTGA...
78  AAATGTCACAACTTTAAGTAAAAATTTAGTATACAAAGTTCAAAGA...
79  GCTCCTCGGTTCATATGGGTGATCCGTTAATTTTAACGATGACGAA...
80  GTCCATCGGCATCGAGACATCAGCATCACCAACAGTACCGGTACGT...
81  TCAATTTCGATTCTCTCAAACTATAGCGGGCGATCGCTGGATACGA...
82  AGATTTGGGTAGCATTTTTTCTAGAAATACTATTAAAATTTTTCCA...
83  GGGTTCGTGTCGTCGTCATTCGGAGGTTGACAGAGCGCGAGAACTG...
84  GACTCCGTGTGTTAGTCAGAAGTGTGGCAAATAGATGTCAAGAATG...
85  CTACAGCTTTTAACGTCGCTTTTTTACAAACGGAGCAAACCCGACA...
86  TTGGAATGAATCATGCCGCCGGAAGAAATAAAAAGGGTTCTGTGTA...
87  GGTACCCCAAGACAATCCAGAATAACTCGGGAACCACGTGGACCAT...
88  AAAGTTCAGAAAAATTTTACGTTTGCTGTCAAATTTTCAAAATTTT...
89  CCTGTTAAACTATAATGTTTGGCGCATCGTCTCATATATGCCCCTA...
90  GGCCTTACAGTTGAGGTCGAAATACGCGTATCTGTCAAAGGATACA...
91  ACACCTAACTGTCGGTTCCGCGTTATTTTCGATTCGACCAATGATA...
92  CATGCGCACTATTGAGAATCCGGAAAGCGACCCGGCGAAGTTGGTC...
93  TGGTATAATCAAAGTTTTCAGGAAAACAATAGCAGTTGAAACAAAA...
94  AAGATAGGCTGCTCCTGAATGAACCAGTCGTGTCCGCACCGAATAC...
95  TTTCAATCTTGTGATATTAAATTTGAGTATATTTGTAGTTCACTGT...
96  AAATTACAAAATTTTTTTTACAGTGTATATTTTTTTTCCAGATAGT...
97  GTTGGCGGATGTAGATAGTACGCGAGGGTTCAATGTCGAATTTAGG...
98  GAACTGTTGAAGACACAGAAAAATACTGAGATCTCCTTCCACTTTT...
99  ACTTTCCAAATAAGTTCAGACTTCTCTTAGATTCCAAAGTATTTAT...

[100 rows x 1 columns]

10) Look back over the various SQL queries you've typed. Which of the following is FALSE?